//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace np_website.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ForumAchievement
    {
        public int AchievementID { get; set; }
        public int UserID { get; set; }
        public System.DateTime DateCreated { get; set; }
        public int TimesAchieved { get; set; }
    }
}
