//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace np_website.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class RaidAttendance
    {
        public int RaidAttendanceId { get; set; }
        public Nullable<int> Group { get; set; }
        public string Name { get; set; }
        public int Level { get; set; }
        public string Class { get; set; }
        public string Role { get; set; }
        public bool Flagged { get; set; }
        public System.DateTime DumpTime { get; set; }
        public int DKP { get; set; }
        public bool Include { get; set; }
        public bool Processed { get; set; }
    }
}
